#!/bin/bash
#
# build-nav.sh — regenerate the site nav in every page from _nav/nav.html (PE-176).
#
# SCOPE: this script does the NAV. It is deliberately not a general templating
# system for the site. Keep it that way.
#
# Guarantees:
#   IDEMPOTENT  — replaces strictly BETWEEN the NAV:BEGIN/NAV:END markers and
#                 never appends. Running it twice yields byte-identical output.
#   FAIL CLOSED — a page in the manifest that is missing either marker, or has
#                 duplicate markers, is a hard ERROR that names the page. No
#                 page is ever silently skipped.
#   EXPLICIT    — pages that intentionally carry no site nav are listed in
#                 EXCLUDED below with a reason, not omitted quietly.
#
# Usage:  tools/build-nav.sh          regenerate
#         tools/build-nav.sh --check  verify up to date, change nothing (exit 1 if stale)
#
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"
NAV_SRC="_nav/nav.html"

# ---------------------------------------------------------------------------
# MANIFEST — every page that carries the site nav.
# ---------------------------------------------------------------------------
PAGES=(
  about.html changelog.html clusters.html contributors.html cpe.html
  crosswalk.html emerging.html engagement.html framework.html governance.html
  index.html matrix.html maturity.html program.html references.html
  reviews.html start.html suggest.html wellness.html
  papers/index.html talks/index.html
)

# EXCLUDED — pages under the webroot that deliberately do NOT carry the site
# nav. Listed explicitly so the omission is a decision on record, not a gap.
#   osit/index.html       standalone deliverable microsite; has no site nav by design
#   fsisacbrc/index.html  standalone deliverable microsite; has no site nav by design
#   (one further page under the webroot is excluded for the same reason: it
#    carries its own in-page nav. Redacted from the public mirror.)
EXCLUDED=( osit/index.html fsisacbrc/index.html )

CHECK_ONLY=0
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=1

[[ -f "$NAV_SRC" ]] || { echo "ERROR: missing $NAV_SRC" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Preflight: every manifest page must exist and have exactly one of each marker.
# Collect ALL problems before exiting so one run reports every bad page.
# ---------------------------------------------------------------------------
problems=0
for p in "${PAGES[@]}"; do
  if [[ ! -f "$p" ]]; then
    echo "ERROR: $p — listed in manifest but not found" >&2; problems=1; continue
  fi
  b=$(grep -c -- '<!-- NAV:BEGIN -->' "$p" || true)
  e=$(grep -c -- '<!-- NAV:END -->' "$p" || true)
  if [[ "$b" -ne 1 || "$e" -ne 1 ]]; then
    echo "ERROR: $p — expected exactly 1 NAV:BEGIN and 1 NAV:END, found ${b} and ${e}" >&2
    problems=1
  fi
done
if [[ "$problems" -ne 0 ]]; then
  echo "" >&2
  echo "Refusing to build. Fix the pages named above, or move them to EXCLUDED" >&2
  echo "in tools/build-nav.sh if they legitimately should not carry the nav." >&2
  exit 1
fi

# Sanity: an EXCLUDED page must not also be in the manifest.
for x in "${EXCLUDED[@]}"; do
  for p in "${PAGES[@]}"; do
    [[ "$x" == "$p" ]] && { echo "ERROR: $x is in both PAGES and EXCLUDED" >&2; exit 1; }
  done
done

# ---------------------------------------------------------------------------
# Canonical nav markup = $NAV_SRC from its first <nav onward (the leading
# authoring comment stays in the partial and is not shipped into pages).
# ---------------------------------------------------------------------------
TMPDIR_B=$(mktemp -d)
trap 'rm -rf "$TMPDIR_B"' EXIT
CANON="$TMPDIR_B/canon.html"
awk '/<nav /{f=1} f' "$NAV_SRC" > "$CANON"
[[ -s "$CANON" ]] || { echo "ERROR: no <nav> found in $NAV_SRC" >&2; exit 1; }

# Canonical URL for a page path: X/index.html -> /X/ ; index.html -> / ; f.html -> /f
# PE-178: the bare-page arm drops the extension. This function exists ONLY to
# find the nav link belonging to the page being generated, so it MUST spell the
# URL exactly as _nav/nav.html now spells it (/framework, not /framework.html).
# Leave it emitting /f.html after the extensionless switch and nothing matches:
# no page gets class="nav-active", silently, with no error from this script.
canonical_url() {
  case "$1" in
    index.html) echo "/" ;;
    */index.html) echo "/${1%index.html}" ;;
    *) echo "/${1%.html}" ;;
  esac
}

changed=(); stale=()
for p in "${PAGES[@]}"; do
  url=$(canonical_url "$p")

  # Build this page's nav: canonical markup + nav-active on the matching link.
  # If the page's own URL is not in the nav (e.g. index, crosswalk, talks),
  # no link is marked active — which is correct, not an error.
  BLOCK="$TMPDIR_B/block.html"
  {
    echo '<!-- GENERATED by tools/build-nav.sh from _nav/nav.html — DO NOT HAND-EDIT.'
    echo '     Edit _nav/nav.html and re-run tools/build-nav.sh; changes here are overwritten. -->'
    awk -v url="$url" '
      {
        if (index($0, "href=\"" url "\"") > 0) {
          sub("href=\"" url "\"", "href=\"" url "\" class=\"nav-active\"")
        }
        print
      }' "$CANON"
  } > "$BLOCK"

  OUT="$TMPDIR_B/out.html"
  awk -v blockfile="$BLOCK" '
    BEGIN { while ((getline l < blockfile) > 0) blk = blk l "\n"; close(blockfile) }
    /<!-- NAV:BEGIN -->/ { print; printf "%s", blk; skip=1; next }
    /<!-- NAV:END -->/   { print; skip=0; next }
    skip { next }
    { print }
  ' "$p" > "$OUT"

  if cmp -s "$p" "$OUT"; then
    continue
  fi
  stale+=("$p")
  if [[ "$CHECK_ONLY" -eq 0 ]]; then
    cat "$OUT" > "$p"        # preserve the existing file's owner/permissions
    changed+=("$p")
  fi
done

if [[ "$CHECK_ONLY" -eq 1 ]]; then
  if [[ ${#stale[@]} -gt 0 ]]; then
    echo "STALE — these pages do not match _nav/nav.html:" >&2
    printf '  %s\n' "${stale[@]}" >&2
    exit 1
  fi
  echo "OK — all ${#PAGES[@]} pages match _nav/nav.html"
  exit 0
fi

echo "nav built from $NAV_SRC"
echo "  pages in manifest: ${#PAGES[@]}"
echo "  pages excluded:    ${#EXCLUDED[@]} (${EXCLUDED[*]})"
if [[ ${#changed[@]} -eq 0 ]]; then
  echo "  changed:           0 (already up to date)"
else
  echo "  changed:           ${#changed[@]}"
  printf '    %s\n' "${changed[@]}"
fi
echo ""
echo "Now verify by diff, not by claim:  git diff --stat"
